import { NextRequest, NextResponse } from 'next/server'
import { confirm } from '@/lib/newsletter-store'

/**
 * GET /api/newsletter/confirm?token=<token>
 *
 * Completes the double opt-in flow. The token was generated by the
 * subscribe endpoint and should arrive in the user's inbox via the
 * configured transactional mail service.
 *
 * Renders a tiny HTML page so the recipient gets feedback even if they
 * come from a mail client link click (no app JS required).
 */
export async function GET(request: NextRequest) {
	const token = request.nextUrl.searchParams.get('token')?.trim()

	if (!token || token.length < 16) {
		return new NextResponse(renderError('Token mancante o non valido.'), {
			status: 400,
			headers: { 'Content-Type': 'text/html; charset=utf-8' },
		})
	}

	try {
		const result = await confirm(token)

		const html = result.ok
			? renderSuccess(result.email)
			: renderError(
					'Il link di conferma non è più valido o è già stato usato. Iscriviti di nuovo per ricevere un nuovo link.',
				)

		return new NextResponse(html, {
			status: result.ok ? 200 : 410,
			headers: {
				'Content-Type': 'text/html; charset=utf-8',
				'Cache-Control': 'no-store',
				'X-Robots-Tag': 'noindex',
			},
		})
	} catch (err) {
		console.error('[Newsletter] confirm failed:', err)
		return new NextResponse(renderError('Errore tecnico. Riprova più tardi.'), {
			status: 500,
			headers: { 'Content-Type': 'text/html; charset=utf-8' },
		})
	}
}

function renderSuccess(email?: string): string {
	const safe = email
		? `Riceverai le nostre email all'indirizzo <strong>${escapeHtml(email)}</strong>.`
		: 'Riceverai le nostre email.'
	return `<!doctype html><html lang="it"><head>
<meta charset="utf-8">
<title>Iscrizione confermata — Trm Sport</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<style>
body{font-family:system-ui,-apple-system,sans-serif;background:#0a0f1c;color:#e2e8f0;
margin:0;padding:2rem;min-height:100vh;display:flex;align-items:center;justify-content:center}
main{max-width:480px;background:#0d1b2e;border:1px solid rgba(0,209,255,.18);
border-radius:16px;padding:2.5rem;box-shadow:0 24px 60px rgba(0,0,0,.4);text-align:center}
h1{font-size:1.5rem;color:#0ea5e9;margin:0 0 1rem}
p{line-height:1.6;margin:0 0 1.5rem}
a.btn{display:inline-block;background:#0ea5e9;color:#fff;text-decoration:none;
padding:.75rem 1.5rem;border-radius:8px;font-weight:600}
</style></head>
<body><main role="main">
<h1>Iscrizione confermata</h1>
<p>${safe}</p>
<p>Puoi cancellarti in qualsiasi momento dal footer di ogni email.</p>
<a class="btn" href="/">Torna al sito</a>
</main></body></html>`
}

function renderError(message: string): string {
	return `<!doctype html><html lang="it"><head>
<meta charset="utf-8">
<title>Conferma non riuscita — Trm Sport</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<style>
body{font-family:system-ui,-apple-system,sans-serif;background:#0a0f1c;color:#e2e8f0;
margin:0;padding:2rem;min-height:100vh;display:flex;align-items:center;justify-content:center}
main{max-width:480px;background:#0d1b2e;border:1px solid rgba(255,99,99,.18);
border-radius:16px;padding:2.5rem;box-shadow:0 24px 60px rgba(0,0,0,.4);text-align:center}
h1{font-size:1.5rem;color:#f87171;margin:0 0 1rem}
p{line-height:1.6;margin:0 0 1.5rem}
a.btn{display:inline-block;background:#0ea5e9;color:#fff;text-decoration:none;
padding:.75rem 1.5rem;border-radius:8px;font-weight:600}
</style></head>
<body><main role="main">
<h1>Conferma non riuscita</h1>
<p>${escapeHtml(message)}</p>
<a class="btn" href="/">Torna al sito</a>
</main></body></html>`
}

function escapeHtml(s: string): string {
	return s.replace(/[&<>"']/g, (c) =>
		c === '&' ? '&amp;' : c === '<' ? '&lt;' : c === '>' ? '&gt;' : c === '"' ? '&quot;' : '&#39;',
	)
}
